import { chromium, devices } from 'playwright';
import fs from 'node:fs';

const BASE = process.env.GJR_BASE_URL || 'https://getjobready.online/';
const DIR = process.env.GJR_AUDIT_FILES || '/tmp/gjr-audit';
const DUMMY_CV = 'Alex Student\nComputer Science Student | alex@example.com\nEducation: B.Tech Computer Science, Example University\nProjects: Built a campus placement tracker using React and Supabase.\nSkills: React, JavaScript, SQL, Python';
const DUMMY_JD = 'Management Trainee Intern\nWork with cross-functional teams, analyse business problems, communicate recommendations, and use data and AI tools to improve execution.';

const results=[];
const failures=[];
const pass=(msg)=>{results.push({kind:'pass',msg});console.log('[PASS]',msg)};
const info=(msg)=>{results.push({kind:'info',msg});console.log('[INFO]',msg)};
const fail=(msg)=>{failures.push(msg);console.error('[FAIL]',msg)};

async function assertText(page,re,label){const body=await page.locator('body').innerText();if(!re.test(body))throw new Error(`${label}: expected ${re}`)}
async function waitForUI(page){await page.waitForTimeout(500);await page.evaluate(()=>window.scrollTo(0,0)).catch(()=>{})}
async function diagnostics(page,label){const d={label,consoleErrors:[],pageErrors:[],failedRequests:[]};page.on('console',m=>{if(m.type()==='error')d.consoleErrors.push(m.text())});page.on('pageerror',e=>d.pageErrors.push(e.message));page.on('requestfailed',r=>d.failedRequests.push(`${r.method()} ${r.url()} :: ${r.failure()?.errorText||'failed'}`));return d}
async function fresh(context,seed={}){const p=await context.newPage();await p.addInitScript(({seed})=>{for(const[k,v]of Object.entries(seed||{}))localStorage.setItem(k,v);try{sessionStorage.clear()}catch{}},{seed});await p.goto(BASE,{waitUntil:'domcontentloaded',timeout:60000});await waitForUI(p);return p}
async function click(page,re,label){const el=page.getByText(re).first();if(!await el.count()||!await el.isVisible().catch(()=>false))throw new Error(`${label}: control not visible`);await el.scrollIntoViewIfNeeded();await el.click({timeout:10000});await waitForUI(page);pass(`${label} clicked`)}
async function upload(page,file,label){const path=`${DIR}/${file}`;if(!fs.existsSync(path))throw new Error(`${label}: missing ${file}`);const input=page.locator('input[type=file]').first();if(!await input.count())throw new Error(`${label}: file input missing`);await input.setInputFiles(path);await waitForUI(page);pass(`${label}: uploaded ${file}`)}
function finishDiagnostics(d){if(d.pageErrors.length)for(const e of d.pageErrors)fail(`${d.label}: page error ${e}`);if(d.consoleErrors.length)info(`${d.label}: console errors ${d.consoleErrors.slice(0,10).join(' | ')}`);if(d.failedRequests.length)info(`${d.label}: failed requests ${d.failedRequests.slice(0,10).join(' | ')}`)}

async function testHome(context,label){const p=await fresh(context),d=await diagnostics(p,label);try{await assertText(p,/GetJobReady/i,`${label} home`);pass(`${label}: homepage loaded`);const how=p.getByRole('button',{name:/How it works/i}).first();if(await how.count()){await how.click();await waitForUI(p);await assertText(p,/How it works|01|Step/i,`${label} how`);pass(`${label}: How it works opened`);await p.keyboard.press('Escape').catch(()=>{})}const t=p.getByRole('button',{name:/Internship|Full-time/i});if(await t.count()>=2){await t.nth(0).click();await t.nth(1).click();pass(`${label}: career toggle exercised`)}for(const re of [/CV Preparation/i,/AI Audio Interview/i,/Corporate Ready/i,/AI at Work/i,/Impress the Interviewer/i]){await p.goto(BASE,{waitUntil:'domcontentloaded',timeout:60000});await waitForUI(p);const c=p.getByText(re).first();if(await c.count()&&await c.isVisible().catch(()=>false)){await c.click();await waitForUI(p);pass(`${label}: ${re} opened`)}else fail(`${label}: feature ${re} not visible`)} }catch(e){fail(`${label}: ${e.message}`)}finally{finishDiagnostics(d);await p.close()}}

async function testAuth(context,label){const p=await fresh(context);try{await p.route('https://lgctkqqgtpnabydukypt.supabase.co/auth/v1/otp**',r=>r.fulfill({status:200,contentType:'application/json',body:'{}'}));const sign=p.getByRole('button',{name:/Sign in/i}).first();if(!await sign.count()){info(`${label}: login control not exposed on current initial state`);return}await sign.click();await waitForUI(p);const email=p.locator('input[type=email]').first();if(!await email.count())throw new Error('auth email field missing');await email.fill('audit@example.com');const send=p.getByRole('button',{name:/Continue|Send secure sign-in/i}).first();if(!await send.count())throw new Error('auth submit missing');await send.click();await waitForUI(p);await assertText(p,/check your email|sign-in link|sync.*devices/i,`${label} auth confirmation`);pass(`${label}: login wiring exercises real Supabase OTP flow`)}catch(e){fail(`${label}: ${e.message}`)}finally{await p.close()}}

async function testCV(context,label){const p=await fresh(context),d=await diagnostics(p,label);try{await click(p,/CV Preparation|Get your CV matched/i,`${label} CV`);await assertText(p,/CV \+ Job Description|General CV Preparation|Your CV/i,`${label} CV screen`);const n=await p.locator('input[type=file]').count();if(n<1)throw new Error('CV file input missing');await upload(p,'dummy-text.pdf',`${label} CV`);if(fs.existsSync(`${DIR}/dummy.docx`))await upload(p,'dummy.docx',`${label} CV`);if(fs.existsSync(`${DIR}/dummy.txt`))await upload(p,'dummy.txt',`${label} CV`);const tas=p.locator('textarea:visible');if(await tas.count()>=2){await tas.nth(0).fill(DUMMY_CV);await tas.nth(1).fill(DUMMY_JD);pass(`${label}: CV and JD fields filled`)}const analyze=p.getByRole('button',{name:/Analyse my fit|Analyze my fit/i}).first();if(await analyze.count()&&await analyze.isVisible().catch(()=>false)){await analyze.click({timeout:20000});await p.waitForTimeout(6000);if(/Improve your CV first|Your Readiness Report|CV Studio/i.test(await p.locator('body').innerText()))pass(`${label}: AI analysis advanced to result/CV studio`);else fail(`${label}: AI analysis did not advance`)}}catch(e){fail(`${label}: ${e.message}`)}finally{finishDiagnostics(d);await p.close()}}

async function testModule(context,label,re,name,fieldText){const p=await fresh(context),d=await diagnostics(p,`${label} ${name}`);try{await click(p,re,`${label} ${name}`);await assertText(p,re,`${label} ${name} page`);const ta=p.locator('textarea:visible').first();if(await ta.count())await ta.fill(fieldText);const btn=p.getByRole('button',{name:/Build my action plan|Generate|Create|Build|Demo/i}).first();if(await btn.count()&&await btn.isVisible().catch(()=>false)){await btn.click({timeout:20000});await p.waitForTimeout(4000);pass(`${label}: ${name} primary action exercised`)}else info(`${label}: ${name} has no matching primary action in current state`)}catch(e){fail(`${label} ${name}: ${e.message}`)}finally{finishDiagnostics(d);await p.close()}}

async function testVoice(context,label){const p=await fresh(context),d=await diagnostics(p,label);try{await p.addInitScript(()=>{class FakeRecognition{start(){this.onstart?.();setTimeout(()=>this.onresult?.({resultIndex:0,results:[{0:{transcript:'I built a placement tracker using React and improved the student workflow.',confidence:0.99},isFinal:true}]}),250)}stop(){this.onend?.()}}window.SpeechRecognition=FakeRecognition;window.webkitSpeechRecognition=FakeRecognition;window.speechSynthesis={cancel(){},speak(u){setTimeout(()=>u.onend?.(),100)},getVoices(){return[{name:'Google English India',lang:'en-IN'}]}}});await click(p,/AI Audio Interview|Talk to your AI interviewer/i,`${label} interview`);await assertText(p,/AI Mock Interview|real conversation|LIVE INTERVIEW/i,`${label} voice page`);const typed=p.getByRole('button',{name:/type \/ paste answer|quiet mode/i}).first();if(await typed.count()&&await typed.isVisible().catch(()=>false)){await typed.click();pass(`${label}: typed fallback opened`)}const start=p.getByRole('button',{name:/start.*conversation|start interview|start/i}).first();if(await start.count()&&await start.isVisible().catch(()=>false)){await start.click();await p.waitForTimeout(1600);pass(`${label}: voice capture state exercised`)} }catch(e){fail(`${label}: ${e.message}`)}finally{finishDiagnostics(d);await p.close()}}

async function testDashboard(context,label){const seed={'gjr_profile':JSON.stringify({email:'audit@example.com',joined:new Date().toISOString()}),'gjr_master_cv_audit_example_com':DUMMY_CV,'gjr_apps_audit_example_com':JSON.stringify([{id:'audit-app-1',role:'Management Trainee Intern',company:'Example Co',cv:DUMMY_CV,jd:DUMMY_JD,result:{score:82,headline:'Good fit',summary:'Strong base'},updated:new Date().toISOString()}]),'gjr_interviews_audit_example_com':JSON.stringify([{id:'audit-iv-1',role:'Management Trainee Intern',score:79,date:new Date().toISOString(),strengths:['Clear communication'],improvements:['Use more metrics'],nextAction:'Add measurable outcomes',answers:[]}])};const p=await fresh(context,seed),d=await diagnostics(p,label);try{await assertText(p,/My Applications/i,`${label} dashboard`);await assertText(p,/Interview History/i,`${label} dashboard`);pass(`${label}: dashboard loaded with seeded history`);const tabs=p.locator('.dash-tabs button:visible');if(await tabs.count()>=2){await tabs.nth(1).click();await waitForUI(p);await assertText(p,/Interview History/i,`${label} history tab`);pass(`${label}: interview history tab clicked`);await tabs.nth(0).click();pass(`${label}: applications tab clicked`)}const controls=p.locator('[role="button"]:visible');const count=await controls.count();info(`${label}: dashboard role-button count=${count}`);for(let i=0;i<count;i++){const q=await fresh(context,seed);try{const c=q.locator('[role="button"]:visible').nth(i);if(await c.count()&&await c.isVisible().catch(()=>false)){await c.click({timeout:5000});pass(`${label}: dashboard control ${i+1} clicked`)}}catch(e){fail(`${label}: dashboard control ${i+1}: ${e.message}`)}finally{await q.close()}}}catch(e){fail(`${label}: ${e.message}`)}finally{finishDiagnostics(d);await p.close()}}

async function run(name,opts){const browser=await chromium.launch({headless:true});const context=await browser.newContext({...opts,permissions:['microphone']});try{await testHome(context,name);await testAuth(context,name);await testCV(context,name);await testModule(context,name,/Corporate Ready/i,'Corporate Ready','I want to improve communication, feedback and workplace confidence.');await testModule(context,name,/AI at Work/i,'AI at Work','Help me learn practical AI workflows for research, writing, analysis and automation.');await testModule(context,name,/Impress the Interviewer/i,'Impress the Interviewer','A company needs to improve access to campus career preparation.');await testVoice(context,name);await testDashboard(context,name)}finally{await context.close();await browser.close()}}

await run('desktop',{viewport:{width:1440,height:900}});
await run('mobile',{...devices['Pixel 7']});
const report={base:BASE,generatedAt:new Date().toISOString(),passed:failures.length===0,results,failures};
fs.writeFileSync('live-audit-report.json',JSON.stringify(report,null,2));
console.log(JSON.stringify(report,null,2));
if(failures.length)process.exitCode=1;
