import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
const read=(file)=>fs.readFileSync(file,'utf8');
const fail=(message)=>{console.error(`FAIL: ${message}`);process.exit(1)};
const expect=(condition,message)=>{if(!condition)fail(message);console.log(`PASS: ${message}`)};
const entry=read('index.src.html');
const app=read('src/main-v2.jsx');
const server=read('server.cjs');
const router=read('ai-router.cjs');
expect(entry.includes('/favicon.svg'),'source entrypoint defines the production favicon');
expect(entry.includes('/src')===false,'source entrypoint does not load legacy browser bridge scripts');
expect(entry.includes('<div id="root"></div>'),'source entrypoint mounts the React application');
expect(app.includes('AI Audio Interview'),'audio interview is present in the student UI');
expect(app.includes("prep==='general"),'general CV preparation mode exists');
expect(app.includes("prep==='specific"),'CV + JD preparation mode exists');
expect(!app.includes('getjobready-ai-proxy.mnijhara.workers.dev'),'browser does not call the AI proxy directly');
expect(app.includes("post('/api/analyze'"),'CV analysis goes through the server API');
expect(app.includes('cv-studio-native'),'native CV improvement studio exists');
expect(app.includes('rewrittenBullets'),'AI CV analysis supplies editable bullet improvements');
expect(app.includes('setEditor(initial'),'uploaded CV is populated before review');
expect(app.includes('Continue to live audio interview'),'CV save gate precedes the interview');
expect(app.includes("post('/api/interview-turn'"),'voice turns go through the server API');
expect(app.includes('SpeechRecognition'),'live interview uses browser speech recognition');
expect(app.includes('speechSynthesis'),'live interview speaks questions aloud');
expect(app.includes('setTimeout(()=>submit(),1800)'),'silence automatically submits spoken answers');
expect(app.includes('No answer buttons'),'student is explicitly told answers are captured automatically');
expect(app.includes('.docx'),'CV upload accepts DOCX files');
expect(app.includes("sessionStorage.getItem('gjr_career')"),'career selection restores from session state');
expect(app.includes("sessionStorage.setItem('gjr_career',v)"),'career selection writes to session state');
expect(app.includes('How it works'),'How it works is implemented in the native React UI');
expect(app.includes('Summer Internship')&&app.includes('Full-time Job'),'career switch offers both tracks');
expect(server.includes("mode === 'general'"),'server has separate general-CV AI logic');
expect(server.includes('ROLE-SPECIFIC CV + JD INTERVIEW'),'server has explicit CV + JD interview logic');
expect(server.includes('CANDIDATE CV:'),'server interview prompts include candidate CV context');
expect(server.includes('X-Content-Type-Options'),'security headers are enabled');
expect(server.includes('Permissions-Policy'),'microphone permissions are explicitly scoped');
expect(server.includes('const allowedOrigin ='),'API CORS policy defines the configured public origin');
expect(server.includes('Too many requests'),'API rate limiting is enabled');
expect(server.includes('app.listen(PORT'),'production server starts successfully');
expect(router.includes('getjobready-ai-proxy.mnijhara.workers.dev'),'AI router uses the server-side Cloudflare AI proxy');
expect(router.includes('Cloudflare 5-key round-robin + automatic failover'),'AI router documents proxy failover');
expect(!/GEMINI_API_KEY_[0-9]+\s*=|AIza[0-9A-Za-z_-]{20,}|sk-[0-9A-Za-z]{20,}/.test(`${entry}\n${app}\n${server}\n${router}`),'no provider API key is committed to product source');
execFileSync(process.execPath,['--check','server.cjs'],{stdio:'inherit'});
console.log('PASS: server.cjs syntax check');
console.log('GetJobReady product verification passed.');
