import fs from 'node:fs';
import { execFileSync } from 'node:child_process';

const read = (file) => fs.readFileSync(file, 'utf8');
const fail = (message) => { console.error(`FAIL: ${message}`); process.exit(1); };
const expect = (condition, message) => { if (!condition) fail(message); console.log(`PASS: ${message}`); };

const entry = read('index.src.html');
const app = read('src/main-v2.jsx');
const audioAuto = read('src/audio-auto.js');
const progressBridge = read('src/progress-bridge.js');
const homeFeed = read('src/home-feed.jsx');
const roadmap = read('src/roadmap-modules.js');
const howItWorks = read('src/how-it-works.js');
const session = read('src/session-context.js');
const server = read('server.cjs');
const router = read('ai-router.cjs');

expect(entry.includes('/src/main-v2.jsx'), 'source production entrypoint uses the React student UI');
expect(entry.includes('/src/audio-auto.js'), 'hands-free audio bridge is loaded');
expect(entry.includes('/src/progress-bridge.js'), 'completed CV and interview progress bridge is loaded');
expect(app.includes('AI Audio Interview'), 'audio interview is present in the student UI');
expect(app.includes("prep==='general'"), 'general CV preparation mode exists');
expect(app.includes("prep==='specific'"), 'CV + JD preparation mode exists');
expect(app.includes('/api/interview-turn'), 'live interview sends turns to the adaptive interview API');
expect(app.includes('SpeechRecognition'), 'live interview uses browser speech recognition');
expect(app.includes('speechSynthesis'), 'live interview speaks questions aloud');
expect(app.includes('.docx'), 'CV upload accepts DOCX files supported by the backend');
expect(app.includes("sessionStorage.getItem('gjr_career')"), 'career selection restores from session state');
expect(app.includes("sessionStorage.setItem('gjr_career',value)"), 'career selection writes to session state');
expect(audioAuto.includes('Hands-free interview:'), 'audio bridge explains hands-free behavior to the student');
expect(audioAuto.includes('silenceTimer=setTimeout(()=>finishAnswer(s),1800)'), 'audio bridge auto-ends an answer after a short silence');
expect(audioAuto.includes("/answer with your voice|speak answer|speak now/i"), 'audio bridge automatically starts each spoken answer');
expect(audioAuto.includes("/done speaking|stop|end answer/i"), 'audio bridge automatically ends each spoken answer');
expect(audioAuto.includes("b.style.display=feedback&&b===feedback?'':'none'"), 'audio controls are hidden during hands-free conversation');
expect(audioAuto.includes("s.querySelector('.transcript p')"), 'audio bridge reads the React live transcript');
expect(progressBridge.includes("url.endsWith('/api/analyze')||url.endsWith('/api/analyze-upload')"), 'successful CV analysis can complete the CV progress track');
expect(progressBridge.includes("url.endsWith('/api/interview-turn')"), 'adaptive interview responses are observed for completion');
expect(progressBridge.includes('body?.done===true'), 'interview progress completes only after the final turn');
expect(progressBridge.includes("mark('cv')")&&progressBridge.includes("mark('interview')"), 'CV and interview completion emit progress events');
expect(homeFeed.includes('gjr-resume'), 'student feed exposes CV preparation shortcut');
expect(homeFeed.includes('gjr-interview'), 'student feed exposes audio interview shortcut');
expect(homeFeed.includes('gjr-readiness'), 'student feed exposes Corporate Ready shortcut');
expect(homeFeed.includes('gjr-ai'), 'student feed exposes AI at Work shortcut');
expect(homeFeed.includes('gjr-demo'), 'student feed exposes Impress the Interviewer shortcut');
expect(homeFeed.includes("markAndOpen('demo',4)"), 'Impress the Interviewer shortcut routes to the fifth shipped module');
expect(homeFeed.includes('data-feed-career'), 'student feed exposes internship/full-time career switch');
expect(homeFeed.includes('setCareer=(value)'), 'career feed has a single state-sync handler');
expect(homeFeed.includes("classList.toggle('active',x.dataset.feedCareer===value)"), 'career feed toggle updates its active visual state immediately');
expect(homeFeed.includes('feed-nav'), 'student feed has persistent mobile navigation');
expect(homeFeed.includes('data-feed-nav'), 'student navigation routes Home, Prepare, Interview and Progress');
expect(homeFeed.includes('gjr_progress_v1'), 'student progress state has a dedicated session key');
expect(homeFeed.includes("writeProgress=(key,status='started')"), 'student progress distinguishes started and completed activities');
expect(homeFeed.includes("p[key]==='completed'"), 'student progress percentage counts completed activities only');
expect(homeFeed.includes("window.addEventListener('gjr-progress'"), 'student progress listens for completion events from modules');
expect(homeFeed.includes('progress-score'), 'Progress navigation includes a completion indicator');
expect(roadmap.includes("function complete(key)"), 'roadmap modules persist completion state after successful AI work');
expect(roadmap.includes("new CustomEvent('gjr-progress'"), 'roadmap modules notify the student feed when an activity completes');
expect(roadmap.includes("complete(d.api==='corporate'?'corporate':d.api==='ai'?'ai':'demo')"), 'roadmap completion maps to the correct student track');
expect(roadmap.includes("document.addEventListener('click'"), 'roadmap modules intercept feed card clicks');
expect(roadmap.includes("if(DATA[title])"), 'roadmap module routing opens shipped modules instead of dead roadmap alerts');
expect(roadmap.includes("'/api/demo'"), 'demo module uses the product demo API');
expect(roadmap.includes("'/api/coach'"), 'roadmap coaching modules use the AI coach API');
expect(roadmap.includes('Selected drill:'), 'AI roadmap requests preserve the selected drill context');
expect(roadmap.includes('gjr-module-company'), 'demo module accepts a target company');
expect(roadmap.includes('&quot;'), 'generated demo HTML escapes quotation marks for iframe embedding');
expect(roadmap.includes('maxlength="6000"'), 'student module responses have a bounded input size');
expect(howItWorks.includes('HOW IT WORKS'), 'How it works experience is implemented');
expect(howItWorks.includes("document.addEventListener('click'"), 'How it works control has an active click handler');
expect(session.includes("sessionStorage.setItem(key,activeCareer())"), 'career selection persists across sessions');
expect(session.includes("body.career=read()"), 'analysis requests use the persisted career selection');
expect(server.includes("mode === 'general'"), 'server has separate general-CV AI interview logic');
expect(server.includes('ROLE-SPECIFIC CV + JD INTERVIEW'), 'server has explicit CV + JD interview logic');
expect(server.includes('ROLE-SPECIFIC CV + JD INTERVIEW. Use BOTH sources'), 'post-interview feedback evaluates both CV and JD');
expect(server.includes('CANDIDATE CV:\\n${String(cv).slice(0,40000)}\\n\\nTARGET JD:'), 'role-specific feedback prompt includes candidate CV and target JD');
expect(server.includes('X-Content-Type-Options'), 'security headers are enabled');
expect(server.includes('Permissions-Policy'), 'microphone permissions are explicitly scoped');
expect(server.includes('const allowedOrigin ='), 'API CORS policy defines the configured public origin');
expect(server.includes('origin === allowedOrigin'), 'API CORS rejects unexpected configured cross-origin requests');
expect(server.includes('RATE_MAX_BUCKETS = 5_000'), 'rate limiter has a bounded memory footprint');
expect(server.includes('cleanupRateBuckets'), 'rate limiter periodically removes stale buckets');
expect(server.includes('Too many requests'), 'API rate limiting is enabled');
expect(server.includes('app.listen(PORT'), 'production server starts successfully');
expect(server.includes("const parts = cvData && cvMime ? [{ text: prompt }, { inlineData: { mimeType: cvMime, data: cvData } }] : [{ text: prompt }];"), 'interview turns send the prompt once and attach uploaded CV context separately');
expect(router.includes('getjobready-ai-proxy.mnijhara.workers.dev'), 'AI router uses the server-side Cloudflare AI proxy');
expect(router.includes('keySlots: configured() ? 5 : 0'), 'AI router exposes the configured five-key proxy capacity without storing keys');
expect(router.includes('Cloudflare 5-key round-robin + automatic failover'), 'AI router documents five-key proxy failover');
expect(!/GEMINI_API_KEY_[0-9]+\s*=|AIza[0-9A-Za-z_-]{20,}|sk-[0-9A-Za-z]{20,}/.test(`${entry}\n${app}\n${audioAuto}\n${progressBridge}\n${homeFeed}\n${roadmap}\n${howItWorks}\n${session}\n${server}\n${router}`), 'no provider API key or plaintext key assignment is committed to product source');

execFileSync(process.execPath, ['--check', 'server.cjs'], { stdio: 'inherit' });
console.log('PASS: server.cjs syntax check');

console.log('GetJobReady product verification passed.');
