import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
const read=(file)=>fs.readFileSync(file,'utf8');
const fail=(message)=>{console.error(`FAIL: ${message}`);process.exit(1)};
const expect=(condition,message)=>{if(!condition)fail(message);console.log(`PASS: ${message}`)};
const entry=read('index.src.html');
const app=read('src/main-v2.jsx');
const homeFeed=read('src/home-feed-v2.js');
const roadmap=read('src/roadmap-modules.js');
const howItWorks=read('src/how-it-works.js');
const session=read('src/session-context.js');
const server=read('server.cjs');
const router=read('ai-router.cjs');
const aiResilience=read('public/ai-resilience.js');
expect(entry.includes('/src/main-v2.jsx'),'source production entrypoint uses the React student UI');
expect(!entry.includes('cv-improvement-flow.js'),'legacy CV overlay is not loaded alongside native CV Studio');
expect(!entry.includes('audio-auto.js'),'legacy audio bridge is not loaded alongside native voice runtime');
expect(app.includes('AI Audio Interview'),'audio interview is present in the student UI');
expect(app.includes("prep==='general"),'general CV preparation mode exists');
expect(app.includes("prep==='specific"),'CV + JD preparation mode exists');
expect(app.includes('https://getjobready-ai-proxy.mnijhara.workers.dev'),'frontend uses the live server-side AI proxy');
expect(app.includes('cv-studio-native'),'native CV improvement studio exists');
expect(app.includes('improvedCV'),'AI produces a complete editable improved CV');
expect(app.includes('setEditor(initial)'),'uploaded CV is populated before AI review');
expect(app.includes('Continue to live audio interview'),'CV save gate precedes the interview');
expect(app.includes('SpeechRecognition'),'live interview uses browser speech recognition');
expect(app.includes('speechSynthesis'),'live interview speaks questions aloud');
expect(app.includes('setTimeout(()=>submit(),1800)'),'silence automatically submits spoken answers');
expect(app.includes('No answer buttons'),'student is explicitly told answers are captured automatically');
expect(app.includes('.docx'),'CV upload accepts DOCX files');
expect(app.includes("sessionStorage.getItem('gjr_career')"),'career selection restores from session state');
expect(app.includes("sessionStorage.setItem('gjr_career',v)"),'career selection writes to session state');
expect(homeFeed.includes('gjr-resume'),'student feed exposes CV preparation shortcut');
expect(homeFeed.includes('gjr-interview'),'student feed exposes audio interview shortcut');
expect(homeFeed.includes('gjr-readiness'),'student feed exposes Corporate Ready shortcut');
expect(homeFeed.includes('gjr-ai'),'student feed exposes AI at Work shortcut');
expect(homeFeed.includes('gjr-demo'),'student feed exposes Impress the Interviewer shortcut');
expect(homeFeed.includes('data-feed-career'),'student feed exposes internship/full-time career switch');
expect(homeFeed.includes('feed-nav'),'student feed has persistent mobile navigation');
expect(homeFeed.includes('gjr_progress_v1'),'student progress state has a dedicated session key');
expect(homeFeed.includes('progress-score'),'Progress navigation includes a completion indicator');
expect(homeFeed.includes("const streakKey='gjr_streak_v1'"),'student feed stores a dedicated preparation streak');
expect(homeFeed.includes('const touchStreak=()=>'),'preparation streak updates from meaningful preparation activity');
expect(roadmap.includes("function complete(key)"),'roadmap modules persist completion state after successful AI work');
expect(roadmap.includes("new CustomEvent('gjr-progress'"),'roadmap modules notify the student feed when an activity completes');
expect(roadmap.includes("'/api/demo'"),'demo module keeps its API integration');
expect(roadmap.includes("'/api/coach'"),'roadmap coaching modules keep their API integration');
expect(howItWorks.includes('HOW IT WORKS'),'How it works experience is implemented');
expect(howItWorks.includes("document.addEventListener('click'"),'How it works control has an active click handler');
expect(session.includes("sessionStorage.setItem(key,activeCareer())"),'career selection persists across sessions');
expect(session.includes('body.career=read()'),'analysis requests use the persisted career selection');
expect(server.includes("mode === 'general'"),'server has separate general-CV AI interview logic');
expect(server.includes('ROLE-SPECIFIC CV + JD INTERVIEW'),'server has explicit CV + JD interview logic');
expect(server.includes('CANDIDATE CV:'),'server interview prompts include candidate CV context');
expect(server.includes('X-Content-Type-Options'),'security headers are enabled');
expect(server.includes('Permissions-Policy'),'microphone permissions are explicitly scoped');
expect(server.includes('const allowedOrigin ='),'API CORS policy defines the configured public origin');
expect(server.includes('Too many requests'),'API rate limiting is enabled');
expect(server.includes('app.listen(PORT'),'production server starts successfully');
expect(router.includes('getjobready-ai-proxy.mnijhara.workers.dev'),'AI router uses the server-side Cloudflare AI proxy');
expect(router.includes('Cloudflare 5-key round-robin + automatic failover'),'AI router documents five-key proxy failover');
expect(aiResilience.includes('normalizeInit'),'browser AI resilience normalizes legacy request payloads');
expect(aiResilience.includes('body.contents[0].parts = parts.slice(1)'),'browser AI resilience removes a duplicated prompt from contents');
expect(!/GEMINI_API_KEY_[0-9]+\s*=|AIza[0-9A-Za-z_-]{20,}|sk-[0-9A-Za-z]{20,}/.test(`${entry}\n${app}\n${homeFeed}\n${roadmap}\n${howItWorks}\n${session}\n${server}\n${router}\n${aiResilience}`),'no provider API key or plaintext key assignment is committed to product source');
execFileSync(process.execPath,['--check','server.cjs'],{stdio:'inherit'});
console.log('PASS: server.cjs syntax check');
console.log('GetJobReady product verification passed.');
