import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Upload,FileText,Target,Mic,Brain,ShieldCheck,Sparkles,ArrowRight,CheckCircle2,Clock3,BarChart3,BriefcaseBusiness,ChevronRight,Play,RefreshCw,Download,Code2,MessageSquareText} from 'lucide-react';
import './styles.css';

const modules=[
 {id:'resume',icon:FileText,title:'CV → Job Match',text:'Upload your CV and the job description. Get a tailored CV strategy, match score and gaps.',tag:'Start here'},
 {id:'interview',icon:Mic,title:'AI Mock Interview',text:'Practice the exact interview you are preparing for and get instant, actionable feedback.',tag:'Practice'},
 {id:'readiness',icon:ShieldCheck,title:'Corporate Ready',text:'Build resilience, communication, workplace confidence and stress-management habits.',tag:'Thrive'},
 {id:'ai',icon:Sparkles,title:'AI at Work',text:'Learn practical AI workflows that make you faster, sharper and more effective at work.',tag:'Future-ready'},
 {id:'demo',icon:Code2,title:'Impress the Interviewer',text:'Turn a company problem into a polished product concept and live HTML demo.',tag:'Stand out'}
];

function App(){
 const [mode,setMode]=useState('home'); const [career,setCareer]=useState('job'); const [cv,setCv]=useState(''); const [jd,setJd]=useState(''); const [fileName,setFileName]=useState(''); const [loading,setLoading]=useState(false); const [result,setResult]=useState(null); const [question,setQuestion]=useState(0); const [answers,setAnswers]=useState([]); const [answer,setAnswer]=useState('');
 const questions=useMemo(()=>result?.interviewQuestions||['Tell me about yourself and why you are interested in this role.','Walk me through a project where you solved a difficult problem.','What would you do in your first 30 days in this role?'],[result]);
 const parseFile=async e=>{const f=e.target.files?.[0];if(!f)return;setFileName(f.name);if(f.type==='text/plain'){setCv(await f.text());return;}setCv(`Uploaded ${f.name}. Use the CV analysis after adding the job description. Browser PDF extraction is enabled in the production build when available.`)};
 const analyze=async()=>{setLoading(true);try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cv,jd,career})});setResult(await r.json());setMode('results')}catch(e){setResult({error:'Could not connect to the AI service. Please try again.',score:0,highlights:[]})}finally{setLoading(false)}};
 const submitAnswer=async()=>{const next=[...answers,{question:questions[question],answer}];setAnswers(next);setAnswer('');if(question+1<questions.length){setQuestion(question+1);return;}setLoading(true);try{const r=await fetch('/api/interview-feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jd,answers:next})});setResult({...result,feedback:await r.json()});setMode('feedback')}finally{setLoading(false)}};
 if(mode==='home')return <Home career={career} setCareer={setCareer} go={setMode}/>;
 if(mode==='resume')return <Workspace title="CV → Job Match" subtitle="Turn your existing CV into a job-specific preparation plan." icon={<Target/>} back={()=>setMode('home')}><Resume cv={cv} jd={jd} setCv={setCv} setJd={setJd} fileName={fileName} parseFile={parseFile} analyze={analyze} loading={loading} career={career}/></Workspace>;
 if(mode==='results')return <Workspace title="Your Job Readiness Report" subtitle="Here is where you stand — and what to do next." icon={<BarChart3/>} back={()=>setMode('home')}><Results result={result} startInterview={()=>{setQuestion(0);setAnswers([]);setMode('interview')}} career={career}/></Workspace>;
 if(mode==='interview')return <Workspace title="AI Mock Interview" subtitle={`Question ${question+1} of ${questions.length} · ${career==='internship'?'Summer internship':'Full-time job'} preparation`} icon={<Mic/>} back={()=>setMode('results')}><Interview q={questions[question]} answer={answer} setAnswer={setAnswer} submit={submitAnswer} loading={loading}/></Workspace>;
 if(mode==='feedback')return <Workspace title="Interview Feedback" subtitle="Specific actions to make your next answer stronger." icon={<MessageSquareText/>} back={()=>setMode('home')}><Feedback data={result?.feedback}/></Workspace>;
 return <Workspace title={modules.find(m=>m.id===mode)?.title||'GetJobReady'} subtitle={modules.find(m=>m.id===mode)?.text||''} icon={<Sparkles/>} back={()=>setMode('home')}><Module id={mode} career={career}/></Workspace>
}

function Home({career,setCareer,go}){return <div className="app"><header><div className="brand"><span className="logo">GJ</span><span>GetJobReady<span className="dot">.online</span></span></div><button className="ghost">How it works</button></header><main className="hero"><div className="eyebrow"><Sparkles size={15}/> AI-powered campus → corporate readiness</div><h1>Your degree got you here.<br/><em>Let's get you job-ready.</em></h1><p className="lead">One workspace to improve your CV, prepare for the exact role, practice AI interviews, build corporate confidence and stand out with real work.</p><div className="career-toggle"><button className={career==='internship'?'active':''} onClick={()=>setCareer('internship')}>☀️ Summer Internship</button><button className={career==='job'?'active':''} onClick={()=>setCareer('job')}>💼 Full-time Job</button></div><button className="primary hero-btn" onClick={()=>go('resume')}>Build my preparation plan <ArrowRight size={18}/></button><div className="proof"><span><CheckCircle2 size={16}/> CV + JD based</span><span><CheckCircle2 size={16}/> AI interview</span><span><CheckCircle2 size={16}/> Actionable feedback</span></div></main><section className="module-grid">{modules.map(m=><button className="module-card" key={m.id} onClick={()=>go(m.id)}><div className="module-top"><span className="module-icon"><m.icon size={21}/></span><span className="pill">{m.tag}</span></div><h3>{m.title}</h3><p>{m.text}</p><span className="card-link">Open <ChevronRight size={16}/></span></button>)}</section><section className="roadmap"><div><span className="eyebrow">THE JOURNEY</span><h2>From campus to confidence.</h2></div><div className="steps"><div><b>01</b><span>Match</span><small>CV + JD</small></div><div><b>02</b><span>Practice</span><small>AI interview</small></div><div><b>03</b><span>Perform</span><small>Corporate ready</small></div><div><b>04</b><span>Stand out</span><small>Build a demo</small></div></div></section><footer>Built for the first 90 days of your career — and the years after.</footer></div>}

function Workspace({title,subtitle,icon,back,children}){return <div className="app"><header><button className="back" onClick={back}>← Back</button><div className="brand"><span className="logo">GJ</span><span>GetJobReady<span className="dot">.online</span></span></div><div/></header><main className="workspace"><div className="workspace-head"><span className="big-icon">{icon}</span><div><div className="eyebrow">YOUR PREPARATION</div><h1>{title}</h1><p>{subtitle}</p></div></div>{children}</main></div>}
function Resume({cv,jd,setCv,setJd,fileName,parseFile,analyze,loading,career}){return <div className="form-grid"><div className="input-card"><div className="label"><FileText size={17}/> Your CV</div><label className="upload"><Upload size={22}/><b>{fileName||'Upload your CV'}</b><span>PDF, TXT or paste your CV text</span><input type="file" accept=".pdf,.txt" onChange={parseFile}/></label><textarea value={cv} onChange={e=>setCv(e.target.value)} placeholder="Or paste your CV content here…"/></div><div className="input-card"><div className="label"><BriefcaseBusiness size={17}/> Target role</div><div className="mini-note">Preparing for a <b>{career==='internship'?'summer internship':'full-time role'}</b></div><textarea className="tall" value={jd} onChange={e=>setJd(e.target.value)} placeholder="Paste the job description here… Include the company, role, responsibilities and requirements."/></div><div className="full action-row"><div><b>Ready to see your gaps?</b><span>We'll turn your CV + JD into a focused preparation plan.</span></div><button className="primary" disabled={loading||(!cv&&!jd)} onClick={analyze}>{loading?<><RefreshCw className="spin"/> Analysing…</>:<>Analyse my fit <ArrowRight size={18}/></>}</button></div></div>}
function Results({result,startInterview,career}){return <div><div className="score-row"><div className="score"><strong>{result?.score||0}</strong><span>/100 match</span></div><div><h2>{result?.headline||'Your preparation starts here.'}</h2><p>{result?.summary||'Add a stronger role-specific story and practice the likely interview areas.'}</p></div></div><div className="result-grid"><section className="panel"><h3>What is working</h3>{(result?.highlights||['Clear academic foundation','Transferable problem-solving skills','Strong motivation to learn']).map((x,i)=><div className="insight good" key={i}><CheckCircle2 size={17}/>{x}</div>)}</section><section className="panel"><h3>Gaps to close</h3>{(result?.gaps||['Add measurable outcomes to your CV','Prepare two STAR stories','Connect your experience directly to the JD']).map((x,i)=><div className="insight gap" key={i}><Target size={17}/>{x}</div>)}</section></div><section className="panel plan"><div><h3>Your 7-day preparation plan</h3><p>Small, specific actions beat generic interview advice.</p></div>{(result?.plan||['Rewrite your top 3 CV bullets around outcomes','Prepare a 90-second introduction','Practice 5 role-specific questions','Research the company and prepare 3 smart questions','Complete one timed mock interview','Build a STAR story bank','Take the final AI interview']).map((x,i)=><div className="plan-item" key={i}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span><small>{i<2?'30 min':'45 min'}</small></div>)}</section><button className="primary wide" onClick={startInterview}><Mic size={18}/> Start AI mock interview</button></div>}
function Interview({q,answer,setAnswer,submit,loading}){return <div className="interview"><div className="question-card"><span className="pill">AI interviewer</span><h2>{q}</h2><p>Take a breath. Structure your answer, use an example and focus on what <b>you</b> did.</p></div><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Type your answer as if you were speaking to the interviewer…"/><div className="interview-actions"><span><Clock3 size={16}/> Aim for 60–90 seconds</span><button className="primary" disabled={!answer.trim()||loading} onClick={submit}>{loading?'Evaluating…':<>Submit answer <ArrowRight size={17}/></>}</button></div></div>}
function Feedback({data}){return <div className="feedback-grid"><div className="feedback-score"><strong>{data?.score||78}</strong><span>interview readiness</span><div className="meter"><i style={{width:`${data?.score||78}%`}}/></div></div><section className="panel"><h3>What you did well</h3>{(data?.strengths||['You answered directly','Your examples showed ownership','Your motivation came through']).map(x=><div className="insight good" key={x}><CheckCircle2 size={17}/>{x}</div>)}</section><section className="panel"><h3>Next answer, improve this</h3>{(data?.improvements||['Use a clear Situation → Action → Result structure','Quantify the impact wherever possible','Finish with what you learned']).map(x=><div className="insight gap" key={x}><Target size={17}/>{x}</div>)}</section><div className="full tip"><Sparkles size={20}/><div><b>Your one high-impact action</b><p>{data?.nextAction||'Record yourself answering the same question again, but lead with the result before explaining the context.'}</p></div></div><button className="primary wide" onClick={()=>location.reload()}><RefreshCw size={18}/> Practice again</button></div>}
function Module({id,career}){const data={readiness:['Corporate Ready','The first 90 days are a transition, not a test.','Build a personal operating system for resilience, communication, feedback and stress management.',['Handle your first difficult feedback conversation','Build a weekly energy and priority plan','Practice stakeholder communication','Learn when to ask for help']],ai:['AI at Work','Your employer expects leverage, not hype.','Learn how to turn AI into a practical work habit — research, writing, analysis, automation and decision support.',['Prompt a better first draft','Turn meeting notes into actions','Analyse a business problem with AI','Automate a repetitive workflow']],demo:['Impress the Interviewer','Don’t just say you can solve problems. Show them.','Choose a company, identify a customer or operational problem, then turn your solution into a clickable product concept.',['Identify the company problem','Define the user and workflow','Generate the product experience','Present the demo with business impact']],}[id]||['GetJobReady','Prepare with purpose.','Build skills that move with you.',['Know your story','Know the role','Practice deliberately','Show your potential']];return <div className="module-page"><div className="module-hero"><span className="eyebrow">{career==='internship'?'INTERNSHIP MODE':'JOB MODE'}</span><h2>{data[0]}</h2><p>{data[1]} {data[2]}</p></div><div className="check-list">{data[3].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b><ChevronRight size={17}/></div>)}</div>{id==='demo'&&<button className="primary" onClick={()=>alert('Demo builder is next: company → problem → solution → live HTML prototype.')}>Start company demo <ArrowRight size={18}/></button>}</div>}

async function main(){createRoot(document.getElementById('root')).render(<App/>)}main();
