import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Upload,FileText,Target,Mic,ShieldCheck,Sparkles,ArrowRight,CheckCircle2,BarChart3,BriefcaseBusiness,ChevronRight,RefreshCw,Code2,MessageSquareText,X,Volume2,Square,Headphones} from 'lucide-react';
import './styles.css';
import './voice.css';

const modules=[
{id:'resume',icon:FileText,title:'CV → Job Match',text:'Upload your CV and target JD. Get a tailored CV strategy, match score and preparation plan.',tag:'Start here'},
{id:'interview',icon:Mic,title:'AI Mock Interview',text:'Have a real voice conversation. The AI asks, listens, probes and adapts to your answers.',tag:'Practice'},
{id:'readiness',icon:ShieldCheck,title:'Corporate Ready',text:'Build resilience, communication, workplace confidence and stress-management habits.',tag:'Thrive'},
{id:'ai',icon:Sparkles,title:'AI at Work',text:'Learn practical AI workflows that make you faster, sharper and more effective at work.',tag:'Future-ready'},
{id:'demo',icon:Code2,title:'Impress the Interviewer',text:'Turn a company problem into a polished product concept and live HTML demo.',tag:'Stand out'}
];

function App(){
 const [mode,setMode]=useState('home'); const [career,setCareer]=useState('job');
 const [cv,setCv]=useState(''); const [jd,setJd]=useState(''); const [fileName,setFileName]=useState(''); const [fileData,setFileData]=useState(null); const [fileMime,setFileMime]=useState('application/pdf');
 const [loading,setLoading]=useState(false); const [result,setResult]=useState(null); const [question,setQuestion]=useState(0); const [answers,setAnswers]=useState([]);
 const questions=useMemo(()=>result?.interviewQuestions||['Tell me about yourself and why you are interested in this role.','Walk me through a project where you solved a difficult problem.','What would you do in your first 30 days in this role?'],[result]);
 const parseFile=async e=>{const f=e.target.files?.[0];if(!f)return;setFileName(f.name);setFileMime(f.type||'application/pdf');if(f.type==='text/plain'){setCv(await f.text());setFileData(null);return;}const reader=new FileReader();reader.onload=()=>{const raw=String(reader.result||'');setFileData(raw.includes(',')?raw.split(',')[1]:raw);setCv('');};reader.readAsDataURL(f);};
 const clearFile=()=>{setFileName('');setFileData(null);setCv('');setFileMime('application/pdf');};
 const analyze=async()=>{setLoading(true);try{const r=fileData?await fetch('/api/analyze-upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data:fileData,mime:fileMime,name:fileName,jd,career})}:await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cv,jd,career})});const data=await r.json();setResult(data);sessionStorage.setItem('gjrInterviewContext',JSON.stringify({jd,career}));setMode('results');}catch{setResult({error:'Could not connect to the AI service. Please try again.',score:0,highlights:[]})}finally{setLoading(false)}};
 const startInterview=()=>{setQuestion(0);setAnswers([]);sessionStorage.setItem('gjrInterviewContext',JSON.stringify({jd,career}));setMode('interview');};
 if(mode==='home')return <Home career={career} setCareer={setCareer} go={setMode}/>;
 if(mode==='resume')return <Workspace title="CV → Job Match" subtitle="Upload your CV and target job description. We'll build the preparation plan around you." icon={<Target/>} back={()=>setMode('home')}><Resume cv={cv} jd={jd} setCv={setCv} setJd={setJd} fileName={fileName} fileData={fileData} parseFile={parseFile} clearFile={clearFile} analyze={analyze} loading={loading} career={career}/></Workspace>;
 if(mode==='results')return <Workspace title="Your Job Readiness Report" subtitle="Here is where you stand — and exactly what to do next." icon={<BarChart3/>} back={()=>setMode('home')}><Results result={result} startInterview={startInterview}/></Workspace>;
 if(mode==='interview')return <Workspace title="AI Mock Interview" subtitle={`A real voice conversation · ${career==='internship'?'Summer internship':'Full-time job'} preparation`} icon={<Mic/>} back={()=>setMode('results')}><VoiceInterview jd={jd} career={career} question={questions[question]} turn={question+1} maxTurns={7} history={answers} onDone={feedback=>{setResult(prev=>({...prev,feedback}));setMode('feedback')}} onTurn={(turnData,spokenAnswer)=>{setAnswers(prev=>[...prev,{question:questions[question],answer:spokenAnswer,evaluation:turnData?.evaluation}]);if(!turnData.done&&turnData.nextQuestion){setResult(prev=>({...prev,interviewQuestions:[...(prev?.interviewQuestions||questions),turnData.nextQuestion]}));setQuestion(q=>q+1);}}}/></Workspace>;
 if(mode==='feedback')return <Workspace title="Interview Feedback" subtitle="Specific actions to make your next answer stronger." icon={<MessageSquareText/>} back={()=>setMode('home')}><Feedback data={result?.feedback}/></Workspace>;
 return <Workspace title={modules.find(m=>m.id===mode)?.title||'GetJobReady'} subtitle={modules.find(m=>m.id===mode)?.text||''} icon={<Sparkles/>} back={()=>setMode('home')}><Module id={mode} career={career}/></Workspace>;
}

function Home({career,setCareer,go}){return <div className="app"><header><div className="brand"><span className="logo">GJ</span><span>GetJobReady<span className="dot">.online</span></span></div><button className="ghost">How it works</button></header><main className="hero"><div className="eyebrow"><Sparkles size={15}/> AI-powered campus → corporate readiness</div><h1>Your degree got you here.<br/><em>Let's get you job-ready.</em></h1><p className="lead">One workspace to improve your CV, prepare for the exact role, have a real AI voice interview, build corporate confidence and stand out with real work.</p><div className="career-toggle"><button className={career==='internship'?'active':''} onClick={()=>setCareer('internship')}>☀️ Summer Internship</button><button className={career==='job'?'active':''} onClick={()=>setCareer('job')}>💼 Full-time Job</button></div><button className="primary hero-btn" onClick={()=>go('resume')}>Build my preparation plan <ArrowRight size={18}/></button><div className="proof"><span><CheckCircle2 size={16}/> CV + JD based</span><span><CheckCircle2 size={16}/> Live voice interview</span><span><CheckCircle2 size={16}/> Adaptive feedback</span></div></main><section className="module-grid">{modules.map(m=><button className="module-card" key={m.id} onClick={()=>go(m.id)}><div className="module-top"><span className="module-icon"><m.icon size={21}/></span><span className="pill">{m.tag}</span></div><h3>{m.title}</h3><p>{m.text}</p><span className="card-link">Open <ChevronRight size={16}/></span></button>)}</section><section className="roadmap"><div><span className="eyebrow">THE JOURNEY</span><h2>From campus to confidence.</h2></div><div className="steps"><div><b>01</b><span>Match</span><small>CV + JD</small></div><div><b>02</b><span>Talk</span><small>AI interview</small></div><div><b>03</b><span>Perform</span><small>Corporate ready</small></div><div><b>04</b><span>Stand out</span><small>Build a demo</small></div></div></section><footer>Built for the first 90 days of your career — and the years after.</footer></div>}

function Workspace({title,subtitle,icon,back,children}){return <div className="app"><header><button className="back" onClick={back}>← Back</button><div className="brand"><span className="logo">GJ</span><span>GetJobReady<span className="dot">.online</span></span></div><div/></header><main className="workspace"><div className="workspace-head"><span className="big-icon">{icon}</span><div><div className="eyebrow">YOUR PREPARATION</div><h1>{title}</h1><p>{subtitle}</p></div></div>{children}</main></div>}

function Resume({cv,jd,setCv,setJd,fileName,fileData,parseFile,clearFile,analyze,loading,career}){return <div className="form-grid"><div className="input-card"><div className="label"><FileText size={17}/> Your CV</div><label className="upload upload-primary"><Upload size={28}/><b>{fileName||'Upload your CV'}</b><span>{fileName?'CV selected — ready for AI analysis':'PDF or TXT · Upload once, we do the reading'}</span><input type="file" accept=".pdf,.txt,application/pdf,text/plain" onChange={parseFile}/></label>{fileName&&<button className="clear-file" type="button" onClick={clearFile}><X size={15}/> Remove file</button>}<div className="or-divider"><span>or paste text instead</span></div><textarea value={cv} onChange={e=>{setCv(e.target.value);if(e.target.value){setFileData(null);setFileName('')}}} placeholder="Paste your CV text here only if you don't have a file…"/></div><div className="input-card"><div className="label"><BriefcaseBusiness size={17}/> Target role</div><div className="mini-note">Preparing for a <b>{career==='internship'?'summer internship':'full-time role'}</b></div><textarea className="tall" value={jd} onChange={e=>setJd(e.target.value)} placeholder="Paste the job description here… Include the company, role, responsibilities and requirements."/><div className="jd-note"><Target size={15}/> Uploading the JD is next — paste it here for now.</div></div><div className="full action-row"><div><b>Ready to see your gaps?</b><span>We'll read the CV, compare it with the JD and create a focused preparation plan.</span></div><button className="primary" disabled={loading||(!cv&&!fileData)||!jd.trim()} onClick={analyze}>{loading?<><RefreshCw className="spin"/> Analysing…</>:<>Analyse my fit <ArrowRight size={18}/></>}</button></div></div>}

function Results({result,startInterview}){return <div><div className="score-row"><div className="score"><strong>{result?.score||0}</strong><span>/100 match</span></div><div><h2>{result?.headline||'Your preparation starts here.'}</h2><p>{result?.summary||'Add a stronger role-specific story and practice the likely interview areas.'}</p></div></div><div className="result-grid"><section className="panel"><h3>What is working</h3>{(result?.highlights||['Clear academic foundation','Transferable problem-solving skills','Strong motivation to learn']).map((x,i)=><div className="insight good" key={i}><CheckCircle2 size={17}/>{x}</div>)}</section><section className="panel"><h3>Gaps to close</h3>{(result?.gaps||['Add measurable outcomes to your CV','Prepare two STAR stories','Connect your experience directly to the JD']).map((x,i)=><div className="insight gap" key={i}><Target size={17}/>{x}</div>)}</section></div><section className="panel plan"><div><h3>Your 7-day preparation plan</h3><p>Small, specific actions beat generic interview advice.</p></div>{(result?.plan||['Rewrite your top 3 CV bullets around outcomes','Prepare a 90-second introduction','Practice 5 role-specific questions','Research the company and prepare 3 smart questions','Complete one timed mock interview','Build a STAR story bank','Take the final AI interview']).map((x,i)=><div className="plan-item" key={i}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span><small>{i<2?'30 min':'45 min'}</small></div>)}</section><button className="primary wide" onClick={startInterview}><Headphones size={18}/> Start live voice interview</button></div>}

function speak(text,onEnd){if(!('speechSynthesis' in window)){onEnd?.();return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-IN';u.rate=.98;u.pitch=1;u.onend=()=>onEnd?.();u.onerror=()=>onEnd?.();window.speechSynthesis.speak(u);}

function VoiceInterview({jd,career,question,turn,maxTurns,history,onDone,onTurn}){
 const recognitionRef=useRef(null);const answerRef=useRef('');const [status,setStatus]=useState('starting');const [transcript,setTranscript]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [started,setStarted]=useState(false);
 const supported=typeof window!=='undefined'&&(window.SpeechRecognition||window.webkitSpeechRecognition);
 const stopListening=()=>{try{recognitionRef.current?.stop()}catch{}};
 const startListening=()=>{if(!supported){setError('Voice input is not supported in this browser. Please use Chrome on Android or desktop.');setStatus('unsupported');return;}answerRef.current='';setTranscript('');setError('');const R=window.SpeechRecognition||window.webkitSpeechRecognition;const r=new R();r.lang='en-IN';r.continuous=true;r.interimResults=true;r.onstart=()=>setStatus('listening');r.onresult=e=>{let finalText='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)finalText+=t+' ';}if(finalText){answerRef.current=(answerRef.current+' '+finalText).trim();setTranscript(answerRef.current)}else{let interim='';for(let i=e.resultIndex;i<e.results.length;i++)interim+=e.results[i][0].transcript;setTranscript((answerRef.current+' '+interim).trim())}};r.onerror=e=>{if(e.error!=='aborted'){setError(e.error==='not-allowed'?'Microphone permission was denied. Please allow microphone access.':'Voice input stopped. Tap the mic to try again.');setStatus('error')}};r.onend=()=>{recognitionRef.current=null;if(status!=='thinking')setStatus(answerRef.current?'ready':'idle')};recognitionRef.current=r;try{r.start()}catch{setStatus('error');setError('Could not start the microphone.')}};
 const submit=async()=>{stopListening();const spoken=answerRef.current.trim()||transcript.trim();if(!spoken||busy)return;setBusy(true);setStatus('thinking');try{const r=await fetch('/api/interview-turn',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jd,career,question,answer:spoken,history,turn,maxTurns})});const data=await r.json();onTurn(data,spoken);if(data.done){setStatus('complete');const msg=data.finalFeedback?.score?`Interview complete. Your readiness score is ${data.finalFeedback.score} out of 100.`:'Interview complete. Here is your feedback.';speak(msg,()=>onDone(data.finalFeedback||{}));}else{setTranscript('');answerRef.current='';setStatus('speaking');speak(data.nextQuestion,()=>startListening());}}catch{setError('The interviewer could not respond. Please try again.');setStatus('error')}finally{setBusy(false)}};
 useEffect(()=>{if(!started)return;setStatus('speaking');setTranscript('');answerRef.current='';speak(question,()=>startListening());return()=>{try{recognitionRef.current?.stop()}catch{};window.speechSynthesis?.cancel()}},[question,started]);
 useEffect(()=>()=>{try{recognitionRef.current?.stop()}catch{};window.speechSynthesis?.cancel()},[]);
 const begin=()=>{setStarted(true)};
 const statusLabel={starting:'Getting ready…',speaking:'AI is speaking…',listening:'Listening — speak naturally',ready:'Answer captured — tap Done',thinking:'AI is thinking…',complete:'Interview complete',idle:'Ready when you are',error:'Voice needs attention',unsupported:'Voice input unavailable'}[status]||status;
 return <div className="voice-interview"><div className="live-card"><div className="live-top"><span className="live-pill"><span className="live-dot"/> LIVE VOICE</span><span>Question {turn} of {maxTurns}</span></div><div className={`voice-orb ${status}`}><div className="orb-ring"/><Mic size={34}/></div><h2>{started?question:'Ready for a real interview?'}</h2><p className="voice-status">{statusLabel}</p>{transcript&&<div className="transcript"><span>You</span><p>{transcript}</p></div>}{error&&<div className="voice-error">{error}</div>} {!started?<button className="primary voice-start" onClick={begin}><Volume2 size={20}/> Start conversation</button>:status==='listening'||status==='ready'?<div className="voice-actions"><button className="mic-button" onClick={stopListening} title="Stop listening"><Square size={18}/></button><button className="primary done-button" disabled={busy||!transcript.trim()} onClick={submit}><CheckCircle2 size={19}/> Done — send answer</button></div>:status==='error'||status==='unsupported'?<button className="primary" onClick={startListening}><Mic size={19}/> Try microphone again</button>:<div className="thinking-bar"><RefreshCw className="spin" size={18}/>{statusLabel}</div>}<small className="voice-tip">AI asks → you speak → AI probes your answer → next question</small></div></div>}

function Feedback({data}){return <div className="feedback-grid"><div className="feedback-score"><strong>{data?.score||78}</strong><span>interview readiness</span><div className="meter"><i style={{width:`${data?.score||78}%`}}/></div></div><section className="panel"><h3>What you did well</h3>{(data?.strengths||['You answered directly','Your examples showed ownership','Your motivation came through']).map(x=><div className="insight good" key={x}><CheckCircle2 size={17}/>{x}</div>)}</section><section className="panel"><h3>Next answer, improve this</h3>{(data?.improvements||['Use a clear Situation → Action → Result structure','Quantify the impact wherever possible','Finish with what you learned']).map(x=><div className="insight gap" key={x}><Target size={17}/>{x}</div>)}</section><div className="full tip"><Sparkles size={20}/><div><b>Your one high-impact action</b><p>{data?.nextAction||'Repeat the interview and lead each answer with the result before the context.'}</p></div></div><button className="primary wide" onClick={()=>location.reload()}><RefreshCw size={18}/> Practice again</button></div>}
function Module({id,career}){const data={readiness:['Corporate Ready','The first 90 days are a transition, not a test.','Build a personal operating system for resilience, communication, feedback and stress management.',['Handle your first difficult feedback conversation','Build a weekly energy and priority plan','Practice stakeholder communication','Learn when to ask for help']],ai:['AI at Work','Your employer expects leverage, not hype.','Learn how to turn AI into a practical work habit — research, writing, analysis, automation and decision support.',['Prompt a better first draft','Turn meeting notes into actions','Analyse a business problem with AI','Automate a repetitive workflow']],demo:['Impress the Interviewer','Don’t just say you can solve problems. Show them.','Choose a company, identify a customer or operational problem, then turn your solution into a clickable product concept.',['Identify the company problem','Define the user and workflow','Generate the product experience','Present the demo with business impact']],}[id]||['GetJobReady','Prepare with purpose.','Build skills that move with you.',['Know your story','Know the role','Practice deliberately','Show your potential']];return <div className="module-page"><div className="module-hero"><span className="eyebrow">{career==='internship'?'INTERNSHIP MODE':'JOB MODE'}</span><h2>{data[0]}</h2><p>{data[1]} {data[2]}</p></div><div className="check-list">{data[3].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b><ChevronRight size={17}/></div>)}</div>{id==='demo'&&<button className="primary" onClick={()=>alert('Demo builder: company → problem → solution → live HTML prototype.')}>Start company demo <ArrowRight size={18}/></button>}</div>}

createRoot(document.getElementById('root')).render(<App/>);
