(()=>{
const DATA={
 'Corporate Ready':{eyebrow:'CORPORATE READY',title:'Build the habits that make you effective at work.',intro:'Practise one realistic workplace situation and get AI coaching on your response.',items:['Give a crisp 60-second project update','Handle critical feedback without becoming defensive','Turn an ambiguous task into clear next steps','Write a professional escalation message','Prepare for your first-week manager conversation'],api:'corporate'},
 'AI at Work':{eyebrow:'AI AT WORK',title:'Use AI like a high-performing employee.',intro:'Choose a workflow, write your first attempt, and get an AI-powered improvement plan.',items:['Turn a long brief into an action plan','Use AI to prepare for a stakeholder meeting','Create a first draft and improve it with critique','Build a reusable prompt for recurring work','Check AI output for accuracy, bias and missing context'],api:'ai'},
 'Impress the Interviewer':{eyebrow:'STAND OUT',title:'Show what you can build, not just what you can say.',intro:'Turn a real company problem into a concise product concept and a self-contained demo.',items:['Choose a real company problem','Define the user and business outcome','Sketch the simplest useful workflow','Generate a lightweight HTML prototype','Prepare the 90-second demo story'],api:'demo'}
};
const css=`.gjr-module-modal{position:fixed;inset:0;z-index:9999;background:#11182799;display:grid;place-items:center;padding:20px}.gjr-module-card{width:min(680px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:28px;padding:28px;box-shadow:0 24px 80px #0003;font-family:Manrope,system-ui,sans-serif}.gjr-module-card h2{font-weight:800;font-size:28px;margin:8px 0}.gjr-module-card p{color:#6e7687;line-height:1.55}.gjr-module-close{float:right;border:0;background:#f1f2f6;border-radius:50%;width:36px;height:36px;font-size:22px;cursor:pointer}.gjr-module-list{display:grid;gap:9px;margin:20px 0}.gjr-module-step{display:flex;gap:13px;align-items:center;padding:14px;border:1px solid #e7e8ee;border-radius:16px;cursor:pointer}.gjr-module-step.active{border-color:#171e31;background:#f7f8fb}.gjr-module-step b{display:grid;place-items:center;width:30px;height:30px;border-radius:10px;background:#171e31;color:#fff;font-size:11px;flex:none}.gjr-module-step span{font-weight:700;font-size:13px}.gjr-module-label{font-size:12px;font-weight:800;text-transform:uppercase;letter-spacing:.08em;color:#697184}.gjr-module-input,.gjr-module-company{width:100%;box-sizing:border-box;border:1px solid #dfe2ea;border-radius:16px;padding:14px;font:500 14px/1.5 inherit}.gjr-module-input{min-height:120px;resize:vertical}.gjr-module-company{margin:8px 0 12px}.gjr-module-actions{display:flex;gap:10px;margin-top:12px}.gjr-module-start,.gjr-module-secondary{border:0;border-radius:14px;padding:14px 18px;font-weight:800;cursor:pointer}.gjr-module-start{background:#171e31;color:#fff;flex:1}.gjr-module-secondary{background:#f1f2f6;color:#171e31}.gjr-module-result{margin-top:18px;padding:18px;border-radius:18px;background:#f7f8fb;line-height:1.55}.gjr-module-result h3{margin:0 0 8px}.gjr-module-result ul{padding-left:20px}.gjr-demo-frame{width:100%;height:360px;border:1px solid #e4e6ed;border-radius:16px;background:#fff;margin-top:14px}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function style(){if(document.getElementById('gjr-module-style'))return;const s=document.createElement('style');s.id='gjr-module-style';s.textContent=css;document.head.appendChild(s)}
async function coach(type,context){const r=await fetch(type==='demo'?'/api/demo':'/api/coach',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(type==='demo'?context:{module:type,context:`Selected drill: ${context.selectedStep}\nModule: ${context.moduleTitle}\nStudent response: ${context.text}`,career:sessionStorage.getItem('gjr_career')||'job'})});if(!r.ok)throw new Error('Request failed');return r.json()}
function complete(key){try{sessionStorage.setItem('gjr_progress_v1',JSON.stringify({...JSON.parse(sessionStorage.getItem('gjr_progress_v1')||'{}'),[key]:'completed'}))}catch{}window.dispatchEvent(new CustomEvent('gjr-progress',{detail:{key,status:'completed'}}))}
function open(title){const d=DATA[title];if(!d)return;style();let selected=0;const m=document.createElement('div');m.className='gjr-module-modal';m.innerHTML=`<div class="gjr-module-card"><button class="gjr-module-close" aria-label="Close">×</button><span class="eyebrow">${d.eyebrow}</span><h2>${d.title}</h2><p>${d.intro}</p><div class="gjr-module-list">${d.items.map((x,i)=>`<div class="gjr-module-step${i===0?' active':''}" data-i="${i}"><b>${String(i+1).padStart(2,'0')}</b><span>${esc(x)}</span></div>`).join('')}</div>${d.api==='demo'?'<label class="gjr-module-label">Company</label><input class="gjr-module-company" placeholder="e.g. Tata, Deloitte, Amazon..." value="" maxlength="120" />':''}<label class="gjr-module-label">Your response / starting point</label><textarea class="gjr-module-input" maxlength="6000" placeholder="Write what you would actually say or do..."></textarea><div class="gjr-module-actions"><button class="gjr-module-secondary gjr-module-close2">Close</button><button class="gjr-module-start">${d.api==='demo'?'Generate my demo':'Get AI coaching →'}</button></div><div class="gjr-module-output"></div></div>`;document.body.appendChild(m);
const steps=[...m.querySelectorAll('.gjr-module-step')],input=m.querySelector('.gjr-module-input'),company=m.querySelector('.gjr-module-company'),out=m.querySelector('.gjr-module-output');steps.forEach(el=>el.addEventListener('click',()=>{steps.forEach(x=>x.classList.remove('active'));el.classList.add('active');selected=Number(el.dataset.i);input.placeholder=d.items[selected]+' — write your first attempt...'}));
const close=()=>m.remove();m.querySelector('.gjr-module-close').onclick=close;m.querySelector('.gjr-module-close2').onclick=close;
m.querySelector('.gjr-module-start').onclick=async()=>{const text=input.value.trim();if(!text){input.focus();return}const btn=m.querySelector('.gjr-module-start');btn.disabled=true;btn.textContent='Working…';out.innerHTML='<div class="gjr-module-result">AI is coaching your response…</div>';try{let data;if(d.api==='demo'){data=await coach('demo',{company:company?.value.trim()||'Target company',problem:d.items[selected]+': '+text,idea:text});out.innerHTML=`<div class="gjr-module-result"><h3>${esc(data.title||'Your product concept')}</h3><p>${esc(data.tagline||'')}</p><ul>${(data.pitch||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${data.html?`<iframe class="gjr-demo-frame" title="Generated demo" sandbox="allow-scripts" srcdoc="${esc(data.html)}"></iframe>`:''}</div>`}else{data=await coach(d.api,{text,selectedStep:d.items[selected],moduleTitle:d.title});const arr=data.actions||data.workflows||data.guardrails||[];out.innerHTML=`<div class="gjr-module-result"><h3>${esc(data.diagnosis||'Your AI coaching')}</h3>${arr.length?`<ul>${arr.slice(0,5).map(x=>`<li>${esc(typeof x==='string'?x:JSON.stringify(x))}</li>`).join('')}</ul>`:''}<p><strong>Next step:</strong> ${esc(data.nextAction||data.weeklyHabit||data.reflectionQuestion||'Repeat the drill with a more specific example.')}</p></div>`}complete(d.api==='corporate'?'corporate':d.api==='ai'?'ai':'demo')}catch(e){out.innerHTML='<div class="gjr-module-result">The AI coach is temporarily unavailable. Your response is still useful — try the drill again shortly.</div>'}finally{btn.disabled=false;btn.textContent=d.api==='demo'?'Generate my demo':'Get AI coaching →'}};
m.addEventListener('click',e=>{if(e.target===m)close()});}
window.gjrOpenModule=title=>open(title);
document.addEventListener('click',e=>{const card=e.target.closest('.module-card');if(!card)return;const title=card.querySelector('h3')?.textContent?.trim();if(DATA[title]){e.preventDefault();e.stopImmediatePropagation();open(title)}},true);
})();