(()=>{
const DATA={
 'Corporate Ready':{eyebrow:'CORPORATE READY',title:'Build the habits that make you effective at work.',intro:'Short, practical drills for communication, ownership, feedback and workplace confidence.',items:['Give a crisp 60-second project update','Handle critical feedback without becoming defensive','Turn an ambiguous task into clear next steps','Write a professional escalation message','Prepare for your first-week manager conversation']},
 'AI at Work':{eyebrow:'AI AT WORK',title:'Use AI like a high-performing employee.',intro:'Learn repeatable workflows you can use from your first week at work.',items:['Turn a long brief into an action plan','Use AI to prepare for a stakeholder meeting','Create a first draft and improve it with critique','Build a reusable prompt for your recurring work','Check AI output for accuracy, bias and missing context']},
 'Impress the Interviewer':{eyebrow:'STAND OUT',title:'Show what you can build, not just what you can say.',intro:'Create a small, credible solution around a company problem and use it as a portfolio conversation starter.',items:['Choose a real company problem','Define the user and the business outcome','Sketch the simplest useful workflow','Build a lightweight HTML prototype','Prepare the 90-second demo story']}
};
const css=`.gjr-module-modal{position:fixed;inset:0;z-index:9999;background:#11182799;display:grid;place-items:center;padding:20px}.gjr-module-card{width:min(560px,100%);max-height:88vh;overflow:auto;background:#fff;border-radius:28px;padding:26px;box-shadow:0 24px 80px #0003}.gjr-module-card h2{font:800 28px Manrope;margin:7px 0}.gjr-module-card p{color:#6e7687;line-height:1.55}.gjr-module-close{float:right;border:0;background:#f1f2f6;border-radius:50%;width:36px;height:36px;font-size:22px}.gjr-module-list{display:grid;gap:9px;margin:20px 0}.gjr-module-step{display:flex;gap:13px;align-items:center;padding:14px;border:1px solid #e7e8ee;border-radius:16px}.gjr-module-step b{display:grid;place-items:center;width:30px;height:30px;border-radius:10px;background:#171e31;color:#fff;font-size:11px}.gjr-module-step span{font-weight:700;font-size:13px}.gjr-module-start{width:100%;border:0;border-radius:14px;padding:14px;background:#171e31;color:#fff;font-weight:800}`;
function open(title){const d=DATA[title];if(!d)return;let s=document.getElementById('gjr-module-style');if(!s){s=document.createElement('style');s.id='gjr-module-style';s.textContent=css;document.head.appendChild(s)}const m=document.createElement('div');m.className='gjr-module-modal';m.innerHTML=`<div class="gjr-module-card"><button class="gjr-module-close">×</button><span class="eyebrow">${d.eyebrow}</span><h2>${d.title}</h2><p>${d.intro}</p><div class="gjr-module-list">${d.items.map((x,i)=>`<div class="gjr-module-step"><b>${String(i+1).padStart(2,'0')}</b><span>${x}</span></div>`).join('')}</div><button class="gjr-module-start">Start this drill →</button></div>`;document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m||e.target.closest('.gjr-module-close')||e.target.closest('.gjr-module-start'))m.remove()})}
document.addEventListener('click',e=>{const card=e.target.closest('.module-card');if(!card)return;const title=card.querySelector('h3')?.textContent?.trim();if(DATA[title]){e.preventDefault();e.stopImmediatePropagation();open(title)}},true);
})();
